name: Dart CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: ./main/budget_buddy  # Set this to the directory containing pubspec.yaml
      run: dart pub get

    - name: Run tests
      working-directory: ./main/budget_buddy  # Ensure this matches the directory containing pubspec.yaml
      run: dart test
