name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Setup Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3' # specify the Flutter version

      - name: Install dependencies
        run: flutter pub get
        working-directory: main/budget_buddy  # Adjust as necessary to the path to your Flutter project

      - name: Run tests
        run: flutter test
        working-directory: main/budget_buddy
