# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      # Install dependencies
      - name: Install dependencies
        run: dart pub get
        working-directory: Final-Year-Project/main/budget_buddy  # Update this path

      # Optional: Verify formatting
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .
      #   working-directory: Final-Year-Project/main/budget_buddy  # Update this path if uncommenting

      # Analyze project source
      - name: Analyze project source
        run: dart analyze
        working-directory: Final-Year-Project/main/budget_buddy  # Update this path

      # Run tests
      - name: Run tests
        run: dart test
        working-directory: Final-Year-Project/main/budget_buddy  # Update this path

